@host = http://127.0.0.1:10887
###
GET /api/ping


HTTP/1.1 500  - Internal Server Error
content-type: application/json
date: Thu, 10 Apr 2025 21:14:47 GMT
content-length: 142
connection: close
###
POST /api/notify

{
    "interests": ["hello"],
    "title": "Test message",
    "body": "This is a test from my testing platform",
    "link": "",
    "source": "My-Laptop",
    "metadata": {
        "server": "macbook-pro"
    }
}
###
GET /api/recent/10
###
GET /api/history/2025-02-20T12:54:19.428978-05:00