name: Deploy to Production
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Prod
        steps:
            - name: ssh deployment
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  key: ${{ secrets.KEY }}
                  script: |
                      cd ~/git/notifapi
                      git pull
                      go build
                      sudo service notifapi restart
